### ISSUE TITLE
Somehow the site loses the css

### ISSUE THREAD

**Issue by janvanveldhuizen** [apvarun/blist-hugo-theme#122]
Can you check what happens on papasmurf.nl?
It works okay locally using hugo server, but after deployment it has problems with the styling.

My repo is in https://gitlab.com/janware/papasmurf.nl

**Comment by janvanveldhuizen** [comment]
It looks like the baseUrl is not taken into account, so that links lose the https prefix

**Comment by nakibrayan3** [comment]
is it fixed the website https://papasmurf.nl looks file ?

**Comment by janvanveldhuizen** [comment]
This was solved by this PR: https://github.com/apvarun/blist-hugo-theme/pull/123
