### ISSUE TITLE
Feature request: hamburger menu

### ISSUE THREAD

**Issue by AntoineSoetewey** [apvarun/blist-hugo-theme#21]
Hello Varun,

This is not really a bug but rather a feature request.

When there are (too) many links in the menu, it is cut on the mobile version.

I managed to put the links below each other when the width of the screen is small:

![Screenshot 2021-12-28 at 14 11 15](https://user-images.githubusercontent.com/17910063/147569809-ef8febe3-d361-4d2a-8359-e80c73428c10.png)

Would it be possible to add the fact that the menu becomes a hamburger menu when the width of the screen becomes small. Like this template: https://www.zerostatic.io/theme/hugo-hero/

For your information, my repo is https://github.com/AntoineSoetewey/elsaetantoine.

Thanks in advance.

Regards,
Antoine

**Comment by apvarun** [comment]
Hey @AntoineSoetewey, this is how the default menu layout of the theme looks.
![image](https://user-images.githubusercontent.com/8411309/147638105-fef4d8f7-f4ff-470d-b4d5-66e6938bef39.png)

I see that you have made some changes to it in your repo － [header.html](https://github.com/AntoineSoetewey/elsaetantoine/blob/master/layouts/partials/header.html)

It is probably the reason why the menu is weird. Can you adapt the changes based on [theme's header](https://github.com/apvarun/blist-hugo-theme/blob/main/layouts/partials/header.html)?

**Comment by AntoineSoetewey** [comment]
Thanks for your reply.

Here is how it looks like by default when there are too many links:

![image](https://user-images.githubusercontent.com/17910063/147638578-7d7e45b8-9a58-4cdf-a662-89e59f82f52e.png)

I had to make changes to header.html because the links are cut if there are too many.

Let me know if I'm not clear.

**Comment by apvarun** [comment]
Thanks for clarifying. I'll send ina PR later for the menu 😉
