### ISSUE TITLE
Emoji

### ISSUE THREAD

**Issue by AntoineSoetewey** [apvarun/blist-hugo-theme#22]
Hello again,

I managed to make everything working, except emojis.

- I added `enableEmoji = true` in [config.toml](https://github.com/AntoineSoetewey/elsaetantoine/blob/master/config.toml#L65)
- just in case (I don't know whether it is needed or not), I also added `enableInlineShortcodes = true` in [config.toml](https://github.com/AntoineSoetewey/elsaetantoine/blob/master/config.toml#L66)
- I then tried to add an emoji at the end of this [page](https://elsaetantoine.com/), but it's not showing as expected:

![Screenshot 2021-12-29 at 11 21 24](https://user-images.githubusercontent.com/17910063/147652241-ac62bb95-4d64-4310-a279-cd89a4cba987.png)

- I tried on other pages, without success

It is probably not a bug, but rather something I am missing.

Any idea how I could fix this?

Thanks in advance for your help.

Regards,
Antoine

**Comment by apvarun** [comment]
@AntoineSoetewey I tried the same thing and it works

Added `enableEmoji=true` in config.toml and `This is a :smile:` incontent/en/page/about.md

Emoji rendered in UI
![image](https://user-images.githubusercontent.com/8411309/148650137-637dc853-6647-4fd9-99d1-befa126e5e4f.png)

**Comment by AntoineSoetewey** [comment]
Thanks for trying on your side.

As you can see in my config.toml file (https://github.com/AntoineSoetewey/elsaetantoine/blob/master/config.toml#L65) I have added `enableEmoji = true`.

And I added `This is a :smile:` in the homepage (https://github.com/AntoineSoetewey/elsaetantoine/blob/master/content/_index.md) and in the histoire page (https://github.com/AntoineSoetewey/elsaetantoine/blob/master/content/histoire.md).

Regards,
Antoine

**Comment by abhinavganguly1987** [comment]
Hello @AntoineSoetewey 
the  reason why you aren't getting the emojis being rendered is because you've defined the config at wrong line(i.e. line no 65).
Define it at line no 5, just below the **theme**. name definition, and you should be good to go.
Cheers, 🍻  😊
Abhi .
![elsa](https://user-images.githubusercontent.com/10762473/151164248-2c467f27-8dfb-476e-b3f8-f11436689ded.png)

**Comment by AntoineSoetewey** [comment]
Thanks a lot !

**Comment by abhinavganguly1987** [comment]
You're welcome @AntoineSoetewey 😊
