### ISSUE TITLE
Dark mode button always visible

### ISSUE THREAD

**Issue by pauloxnet** [apvarun/blist-hugo-theme#25]
I liked the new hamburger button for mobile resolution but I think also in smaller screen it would be very helpful to have the dark mode button always visible, because this type of button is used a lot on a mobile device.

Maybe it can be moved before the hamburger button.

**Comment by rothgar** [comment]
Would it be useful to default to whatever mode the OS says it's in (default light mode)? Many browsers and OSs support passing through light or dark mode so the theme could automatically switch.

**Comment by apvarun** [comment]
With changes in #44, darkmode will default to OS default unless user manually sets it
