### ISSUE TITLE
Possible to add custom colors?

### ISSUE THREAD

**Issue by BurgerhoutJ** [apvarun/blist-hugo-theme#26]
First of all, great theme, but I want to use my own color palette.
Is that possible?

**Comment by apvarun** [comment]
Hi @BurgerhoutJ 
It is possible to add new colors to `tailwind.config.js` file ([reference](https://tailwindcss.com/docs/customizing-colors#using-custom-colors)). Once added there, you can update the accentColor in site config.toml
