### ISSUE TITLE
Support twitter and opengraph meta tags

### ISSUE THREAD

**Issue by rothgar** [apvarun/blist-hugo-theme#27]
I love the emphasis on images in this theme. Is it possible to also support meta tags for social link previews?

https://ogp.me/ and https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image

I did a couple tests and tried to search the code but I didn't see any support for social previews.

**Comment by apvarun** [comment]
Hey @rothgar Both of them are already supported. 

You can check how to utilise it at site level or page level here: 
https://gohugo.io/templates/internal/#configure-open-graph
https://gohugo.io/templates/internal/#configure-twitter-cards
