### ISSUE TITLE
Set width on the "about" page

### ISSUE THREAD

**Issue by BurgerhoutJ** [apvarun/blist-hugo-theme#35]
Question:

How can I set the page width of the About page. I can't find it, or my knowledge is not that good.
The problem is, that I have a 3 column table and the one column is smaller than the others.

Hope that someone can answer my question.

**Comment by apvarun** [comment]
Currently, it is not possible to change width. Providing option to set width would affect responsiveness of the theme and may break if not configured correctly.

**Comment by BurgerhoutJ** [comment]
Oke.
