### ISSUE TITLE
GoogleAnalytics is not working

### ISSUE THREAD

**Issue by BurgerhoutJ** [apvarun/blist-hugo-theme#36]
I have set the googleAnalytics = "G-MEASUREID" in the config.toml, but I don't see any traffic in Google Analytics. 
Do I'm missing some here?

**Comment by sumodirjo** [comment]
Hi @BurgerhoutJ,

Blist currently use Google Analytics v3 template, see :  https://github.com/apvarun/blist-hugo-theme/blob/279d9368e6d1d69ce46c9aa6c1517da3922f7659/layouts/partials/footer.html#L22

From https://gohugo.io/templates/internal/#use-the-google-analytics-template : 

> When using Google Analytics v4 use _internal/google_analytics.html

As workaround, you can copy the footer.html from the themes to `layouts/partials/footer.html` on the site hugo directory and replace line 22 with `{{ template "_internal/google_analytics.html" . }}`

**Comment by apvarun** [comment]
This issue has been fixed by @AntoineSoetewey

**Comment by AntoineSoetewey** [comment]
In https://github.com/apvarun/blist-hugo-theme/pull/42
