### ISSUE TITLE
POSTCSS: failed to transform "css/styles.css"

### ISSUE THREAD

**Issue by revanmd** [apvarun/blist-hugo-theme#4]
When i try to preview the site by following the quick preview steps, i got this error :

```
Start building sites … 
hugo v0.85.0 linux/amd64 BuildDate=2021-07-05T14:33:29Z
Error: Error building site: POSTCSS: failed to transform "css/styles.css" (text/css). Check your PostCSS installation; install with "npm install postcss-cli". See https://gohugo.io/hugo-pipes/postcss/
Built in 49 ms
```

My hugo version is :
hugo v0.85.0 linux/amd64 BuildDate=2021-07-05T14:33:29Z

I have tried to install postcss globally but give the same error. How i resolve this error ?

Sorry if i'm wrong, cz i'm new in hugo.
Thanks

**Comment by apvarun** [comment]
The easiest way is to copy the package.json file from the theme folder to the hugo project root folder and then run npm install (make sure you have [node js](https://nodejs.org/en/) installed before running this command)

Once this is done, hugo serve would work. This step is a one-time process.

I will include it in the readme as well

**Comment by Enforcer007** [comment]
Still getting issues. 

Copied the package json from themes/blist folder to the project root folder. 
Ran npm install and then hugo serve.

Below is the error.

```shell
❯ hugo serve
Start building sites …
hugo v0.87.0+extended linux/amd64 BuildDate=2021-08-03T13:16:42Z
Error: Error building site: POSTCSS: failed to transform "css/styles.css" (text/css): TypeError: Object.fromEntries is not a function
    at Object.<anonymous> (/home/profitalgo/Personal/quickstart/themes/blist/node_modules/tailwindcss/lib/jit/corePlugins.js:242:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/profitalgo/Personal/quickstart/themes/blist/node_modules/tailwindcss/lib/jit/lib/setupContextUtils.js:36:43)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
Built in 1058 ms
```

config.toml of root folder
```toml
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "blist"
```

**Comment by AntoineSoetewey** [comment]
Having the same issue.

@Enforcer007, did you manage to fix it?

**Comment by Enforcer007** [comment]
@AntoineSoetewey Nope

**Comment by AntoineSoetewey** [comment]
Dear @apvarun,

- I installed the last version of node js
- I added the `package.json` and `package-lock.json` files in the root folder
- I ran `npm install` (and even `install postcss-cli` as suggested in the error message)

However, I still have an issue:

![Screenshot 2021-12-27 at 17 36 46](https://user-images.githubusercontent.com/17910063/147490728-4e4cbd02-e4d4-4f74-9598-9eb77b267de6.png)

Any idea how to fix this?

Your theme looks great, so I'd really like to use it.

Thanks in advance.

Regards,
Antoine

**Comment by apvarun** [comment]
Hey @AntoineSoetewey and @Enforcer007 ,

I tried to replicate this issue and seem to work as intended. Here are the steps I followed.

```
hugo new site test-blist
cd test-blist
git clone https://github.com/apvarun/blist-hugo-theme.git themes/blist
cp themes/blist/package.json ./package.json
cp themes/blist/package-lock.json ./package-lock.json
npm install
npm i -g postcss-cli
echo "theme = \"blist\"" >> config.toml
hugo serve
```

**Installed versions:**
POSTCSS: 9.1.0
Hugo version: 0.82.1


If this is not working, please share the version of postcss and hugo that you are using.

**Comment by AntoineSoetewey** [comment]
Works perfectly with this code ! Thanks, and great theme

**Comment by soulrrrrr** [comment]
Hi, after following the instructions above, I have this problem:
`"/mnt/c/Users/USER/Desktop/aa/hugo_test/blast/layouts/partials/head.html:24:48": execute of template failed: template: partials/head.html:24:48: executing "partials/head.html" at <resources>: can't evaluate field PostProcess in type interface {}`
Version:
postcss: 8.4.8
hugo: 0.68.3
on WSL2
Thanks!

**Comment by apvarun** [comment]
Hey @soulrrrrr this theme is compatible only with version v0.82.1 and above only.
Although 0.68 supports postcss, it has limitations in parsing values that are not formatted as required.

**Comment by soulrrrrr** [comment]
@apvarun Thanks! After upgrade Hugo's version, it works properly.
