### ISSUE TITLE
Remove Dates From Thumbnail Option

### ISSUE THREAD

**Issue by DanielBrett** [apvarun/blist-hugo-theme#50]
Hi,

I was wondering if there is an easy way to remove the dates from the thumbnail images without editing the theme itself (like a toggle in the toml maybe?).  

Similarly an option to remove the posted date, read-time, and wordcount on pages would be nice too.

I'm hoping to be able to do this without tweaking the theme so that we can benefit from future updates to the theme without having to re-edit it each time.

Thanks,

Daniel

**Comment by thePHTest** [comment]
Was this every implemented? I'd like to use this theme as a portfolio rather than a blog. So I'd like to manually set the sort order of the different thumbnails and remove the dates too.

**Comment by DanielBrett** [comment]
Hi,

We ended up just going in and editing the theme itself.  Not ideal as it means we are locked in to the version of the theme from when we made the changes (unless we manually update it with changes).  It would still be nice to see this change implemented someday as we really like the look and feel of Blist!  (Especially the built in dark mode toggle!)

Thanks,

Daniel

**Comment by Ravinou** [comment]
Hi @DanielBrett

I was starting to add an option but it actually exists...

Since this commit : https://github.com/apvarun/blist-hugo-theme/commit/765bcb064c49f924fd3e33ff5c4ddd85afbddc4e

You can use in config.toml : 
```
  # Used to hide the post metadata such as posted date, reading time and word count
  # Can be used at site level or page level
  hideMeta = false
```

For me, this issue can be close, what do you think @apvarun ?

**Comment by apvarun** [comment]
The `hideMeta` option will remove the dates from thumbnails but also remove the other metadata such as reading time and word count from post page. If that works for you, happy to close this issue.

**Comment by DanielBrett** [comment]
Aha!  That would indeed do what we hoped.  Sorry I missed that option!

Thank you for the reply.  I am happy to have this issue closed.

Thanks,

Daniel
