### ISSUE TITLE
Search function doesn't work

### ISSUE THREAD

**Issue by nataliepjlin** [apvarun/blist-hugo-theme#52]
I download this template directly, but the search function just doesn't work. The console shows that it is linked to my homepage (username.github.io/index.json) instead of username.github.io/repo/index.json. Is there any ways I can fix this? Thanks a lot:)

**Comment by Ravinou** [comment]
Search function works on my blog https://r4ven.fr
Search function don't work only on mobile, responsive is broken on the search function.

I don't understand your problem sry :/

Can you link me your website ?

**Comment by Vintagewally** [comment]
I also encountered the same issue. 
Search Widget does not work with the multilanguage version, same for the Netlify CMS.
I just realized that by trial and error, unfortunately I've no idea how to fix it with code.
Other than that merci bcp! c'est un très bon theme.

**Comment by Vintagewally** [comment]
ps. try to set DefaultContentLanguageInSubdir = false in subdirectory and you will see the difference.

**Comment by apvarun** [comment]
This has been fixed in the theme.
