### ISSUE TITLE
How to add custom css?

### ISSUE THREAD

**Issue by sebfischer83** [apvarun/blist-hugo-theme#56]
How can I add custom css to this theme?

**Comment by ToArtur** [comment]
I'm kinda in the same issue. I'm currently trying to customize and can't find a good way to modify it

**Comment by Ravinou** [comment]
Hi @ToArtur and @sebfischer83 , in theme BLIST you have a file style.css in assets > css > styles.css

Copy this file style.css and move it in your website root folder to : assets > css > styles.css (**if folders don't exists, create it !**). Now you can edit this file (don't touch the original lines, **only add lines** !) and add your own CSS, it will override the theme.

Hoping to have helped you.

Have a good day !

**Comment by sebfischer83** [comment]
Thanks!
