### ISSUE TITLE
Getting the theme to run in Windows

### ISSUE THREAD

**Issue by chrisjlocke** [apvarun/blist-hugo-theme#58]
I've installed Hugo in Windows, and got the same POSTCSS error similar to https://github.com/apvarun/blist-hugo-theme/issues/4.
The solution about npm and installing files is a bit 'borked' here - I've no idea on how to install POSTCSS in Windows...
Is this possible, or is this theme just not Windows friendly due to the extra packages needed.

**Comment by apvarun** [comment]
The theme does work with Windows too.

You can install postcss with this command `npm i -g postcss-cli`. The additional requirement for the theme is to have Node installed in your machine.

**Comment by chrisjlocke** [comment]
The missing piece.  Thanks. :)
