### ISSUE TITLE
Possible to add RSS?

### ISSUE THREAD

**Issue by workplacedudes** [apvarun/blist-hugo-theme#63]
Hi,

Is it possible to add RSS to the website? Something like domain.tld/rss?

**Comment by Ravinou** [comment]
Hi @workplacedudes it's on` domain.tld/index.xml` by default or for a section like Blog or others, by default on `domain.tld/<SECTION>/index.xml`

Let me know if it's okay for you.

**Comment by Ravinou** [comment]
@apvarun you can close this.

**Comment by apvarun** [comment]
Thanks for addressing it @Ravinou
