### ISSUE TITLE
How to activate utteranc.es

### ISSUE THREAD

**Issue by mertbozkir** [apvarun/blist-hugo-theme#64]
**What is the snippet to activate utteranc.es comment feature in config.toml file?**

**Comment by prathamdupare** [comment]
I paste the script tag generated on [utteranc.es](https://utteranc.es/) in default.md file. So whenever I create a new blog file comments section gets generated automatically.

**Comment by pulkitkrishna00** [comment]
Where is the "default.md" file located?

**Comment by pulkitkrishna00** [comment]
> I paste the script tag generated on [utteranc.es](https://utteranc.es/) in default.md file. So whenever I create a new blog file comments section gets generated automatically.

Where is the "default.md" file located?

**Comment by sramekmichal** [comment]
Probably in `/archetypes` folder.

**Comment by sramekmichal** [comment]
I was able to activate it like this:
1) Filled a form at https://utteranc.es/
2) Switched my repo to `public`
3) Installed https://github.com/apps/utterances to my repo
4) Checked, if the issues feature was turned on in my repo
5) Copied script from utterance:
```
<script src="https://utteranc.es/client.js"
  repo="<user/repo>"
  issue-term="title"
  label="<my-label>"
  theme="preferred-color-scheme"
  crossorigin="anonymous"
  async>
</script>
``` 
into `/layouts/partials/comments.html` inside my root file.
6) Copied `/themes/blist/layouts/_default/single.html` into `/layouts/_default/single.html` inside my root file.
7) Added:
```
  <div class="article-container"></div>
  {{- partial "comments.html" . }}
  </div>
```
at the end of `single.html` (inside my root folder), just before `{{- partial "social.html" . -}}`.

**Comment by chris-gillatt** [comment]
I wrote a blog about how to get this working here https://howinteresting.co.uk/blog/2022-08-28-blog-comments-using-github-and-utterances/

However, Utterances is not maintained, and I'd recommend using Gisgus instead which does the same thing.  I wrote a blog about that too here: https://howinteresting.co.uk/blog/2022-09-03-blog-comments-using-github-and-giscus/

**Comment by sramekmichal** [comment]
I was able to activate giscus at the same way as utterances 💯

**Comment by apvarun** [comment]
I think we can support this as a config in the theme without any html editing

**Comment by chris-gillatt** [comment]
That'd be great because I have to fork this theme to add Giscus in at the moment. It'd be nice to just have this repo as the upstream.
