### ISSUE TITLE
Is it possible to change number of posts in blog page?

### ISSUE THREAD

**Issue by prathamdupare** [apvarun/blist-hugo-theme#67]
There are only 6 posts visible, and you have to move to second page to see more, please help.

**Comment by Ravinou** [comment]
Hi @prathamdupare , I'll answer you although I didn't appreciate the form of your request :)
That being said, 

* For the main page : you can modify this theme file (or move it to your tree for future updates) : themes/blist/layouts/index.html 

Modify this line : 
```html
{{ range first 6 (where .Site.RegularPages.ByDate.Reverse "Type" $frontBundle)  }}
```
Change the number 6 by the one you want.

* For the blog page, the file is here : themes/blist/layouts/_default/list.html . Change the number.

Have a good night.

**Comment by Ravinou** [comment]
* For the main page : you can modify this theme file (or move it to your tree for future updates) : themes/blist/layouts/index.html 

Modify this line : 
```html
{{ range first 6 (where .Site.RegularPages.ByDate.Reverse "Type" $frontBundle)  }}
```
Change the number 6 by the one you want.

* For the blog page, the file is here : themes/blist/layouts/_default/list.html . Change the number.

Have a good night.

**Comment by prathamdupare** [comment]
Thank you!
