### ISSUE TITLE
Search results broken on https://blist.vercel.app/en/

### ISSUE THREAD

**Issue by chris-gillatt** [apvarun/blist-hugo-theme#68]
Search results broken on demo site https://blist.vercel.app/en/

Steps to reproduce:

1. Visit https://blist.vercel.app/
2. Click Search icon
3. Search for a keyword eg "blog"
4. Click the top result
5. Redirected to http://localhost:5000/blog/emoji-support/

**Comment by apvarun** [comment]
@chris-gillatt Thanks for reporting. This has been fixed ;)
