### ISSUE TITLE
Twitter Shortcode appears broken

### ISSUE THREAD

**Issue by chris-gillatt** [apvarun/blist-hugo-theme#70]
If you take a look at the Twitter post embedder, images in tweets don't appear to resolve:

See **Twitter Simple Shortcode** on the demo site:
https://blist.vercel.app/en/blog/rich-content/

Using `{{< twitter_simple 1557658979018440705 >}}` throws a warn on a local `hugo serve` build too, suggesting you specify both the tweet user and tweet ID like so:

`{{< tweet user="KawaaiMayumi" id="1557658979018440705" >}}`

However, doing a `hugo serve` using the new pattern builds and renders fine, _but_ hugo fails to build in Netlify with the following error:

```
9:57:10 PM: hugo v0.85.0-724D5DB5+extended linux/amd64 BuildDate=2021-07-05T10:46:28Z VendorInfo=gohugoio
9:57:14 PM: Error: Error building site: "/opt/build/repo/content/blog/hugo-rich-content.md:33:6": failed to render shortcode "tweet": failed to process shortcode: template: _internal/shortcodes/tweet.html:6:82: executing "_internal/shortcodes/tweet.html" at <index .Params 0>: error calling index: value has type int; should be string
9:57:14 PM: Total in 4178 ms
9:57:14 PM: ​
9:57:14 PM: ────────────────────────────────────────────────────────────────
9:57:14 PM:   "build.command" failed                                        
9:57:14 PM: ────────────────────────────────────────────────────────────────
9:57:14 PM: ​
9:57:14 PM:   Error message
9:57:14 PM:   Command failed with exit code 255: npm i && HUGO_ENVIRONMENT=production hugo --gc (https://ntl.fyi/exit-code-255)
9:57:14 PM: ​
9:57:14 PM:   Error location
9:57:14 PM:   In Build command from Netlify app:
9:57:14 PM:   npm i && HUGO_ENVIRONMENT=production hugo --gc
9:57:14 PM: ​
9:57:14 PM:   Resolved config
9:57:14 PM:   build:
9:57:14 PM:     command: npm i && HUGO_ENVIRONMENT=production hugo --gc
9:57:14 PM:     commandOrigin: ui
9:57:14 PM:     publish: /opt/build/repo/public
9:57:14 PM:     publishOrigin: ui
9:57:15 PM: Caching artifacts
```

Any ideas?

**Comment by apvarun** [comment]
The issue is because of the Hugo version difference in your local machine and netlify. Hugo updated their shortcode to include user ID also for tweet in newer versions.

So if its working for you locally, make sure to set the same hugo version in netlify also. Refer: https://docs.netlify.com/integrations/frameworks/hugo/#hugo-version

**Comment by chris-gillatt** [comment]
@apvarun -You were correct with my site, Netlify was building on 0.83 and my local version was 0.101, so thanks for that.  The site now builds and the tweet loads and the embedded image renders correctly. 👍 

The tweet is still broken on your test site though.  Could it be a simialr issue? https://blist.vercel.app/en/blog/rich-content 

<img width="834" alt="Screenshot 2022-08-17 at 21 37 06" src="https://user-images.githubusercontent.com/9963006/185239047-87838b22-775c-4584-82f8-69634eba7f41.png">

The tweet should render like so (complete with the image)

<img width="581" alt="Screenshot 2022-08-17 at 21 38 09" src="https://user-images.githubusercontent.com/9963006/185239121-b5b4dc10-6a65-4651-8aea-4cb350d549bf.png">

**Comment by apvarun** [comment]
This is intentional. In the [example site content](https://github.com/apvarun/blist-hugo-theme/blob/main/exampleSite/content/en/blog/rich-content.md), we use `twitter_simple` hugo shortcode instead of `tweet` shortcode.
The simple one avoids loading twitter's javascript into the page thereby preventing any kind of tracking from them.

**Comment by chris-gillatt** [comment]
Great - thanks for the explaination 👍
