### ISSUE TITLE
CSS Compatibility with Github project pages

### ISSUE THREAD

**Issue by wiktorn** [apvarun/blist-hugo-theme#72]
When deploying to Github project pages (or probably any non-root directory) fonts are not loaded, as they refer to absolute path (example [here](https://github.com/apvarun/blist-hugo-theme/blob/main/assets/css/site.css#L13)).

Is there any recommended way to provide prefix to font resources in CSS?

**Comment by apvarun** [comment]
I think its better to update the file directly in this case since hugo doesn't have ways to update this path in CSS file. But I think it's a good tradeoff to have for not using google fonts in the site.
