### ISSUE TITLE
Markdown code input isn't rendering as expected.

### ISSUE THREAD

**Issue by Lovecore** [apvarun/blist-hugo-theme#78]
I noticed that the blog template is not converting the inline `code` function from markdown to HTML. It's displaying the backtick and putting it and the content after in bold. I thought it might have been me, but I checked the demo page, and it also exhibits the same issue.

Example:
https://blist.vercel.app/en/blog/markdown-syntax/

The inline markdown within tables shows this.

Am I missing something? Should I be modifying my `config.toml` with something additional to support single backtick quotes?

**Comment by sramekmichal** [comment]
Exactly what I was thinking.

<img width="777" alt="Snímek obrazovky 2022-10-19 v 7 34 22" src="https://user-images.githubusercontent.com/115155195/196605621-37caa407-0e7b-4b8a-902f-55d66db54dc9.png">

You can see that the `code` is showing as bold with backtick.

The html looks like this:

```
<code>
::before
"code"
::after
</code>
```

It takes values from `styles.min.17b0bf9e9feefdbeec26bf09f165d3dd6e88a2690d0e05678797d446f5fb0f67.css`
```
.prose code::before {
    content: "`";
}
```
```
.prose code::after {
    content: "`";
}
```

It should be simple fix. 

I am just worry that in case of technical writing, this could lead to disliking the blog.

**Comment by chris-gillatt** [comment]
It'd be good to get this fixed, to keep inline code blocks tidy without displaying the back ticks.
