### ISSUE TITLE
Search is indexing only article's Titles

### ISSUE THREAD

**Issue by sramekmichal** [apvarun/blist-hugo-theme#79]
All indications are that the search function only looks for words from the **Titles**.

It does not index **Author**, **Description**, **Text Body** or even **Tags**.

I don't want to criticize here, the theme is really great 👍🏻 

IMHO it's just not practical.
The user may need to search for articles by author.

Is there way to improve this?

**Comment by apvarun** [comment]
Addressed via a [new config](https://github.com/apvarun/blist-hugo-theme/blob/main/exampleSite/config.toml#L100)

**Comment by sramekmichal** [comment]
I am not quite sure, if this really works :-(

**Comment by anitguru** [comment]
This is searching for titles only (still).  It's even evident within the demo.  Any plans to correct this?
