### ISSUE TITLE
Multi Language support

### ISSUE THREAD

**Issue by pgrunm** [apvarun/blist-hugo-theme#81]
Hello,

I really like your theme, but I'm wondering if there is a way to use the theme for multiple languages?

**Comment by apvarun** [comment]
@pgrunm The theme already has support for multiple languages. You can refer the example site [content](https://github.com/apvarun/blist-hugo-theme/tree/main/exampleSite/content) for adding multiple languages to your site.

**Comment by pgrunm** [comment]
Thx for the info, that helps me a lot :)
