### ISSUE TITLE
Add mastodon icon?

### ISSUE THREAD

**Issue by AmarOk1412** [apvarun/blist-hugo-theme#87]
Hi and thank you for this work, it's nice!

I think in social icons, a mastodon icon should be added as it's more and more used!

Have a nice day!

**Comment by Ravinou** [comment]
@AmarOk1412 I just PR to add support. It's on my website you can check the result at https://r4ven.fr/ and add theses modification if you don't want to wait the merge of PR :+1:

**Comment by AmarOk1412** [comment]
aha I was thinking to do it for https://cha-cu.it, so now I don't need to do it!
