### ISSUE TITLE
Skip thumbnail in blog post entry

### ISSUE THREAD

**Issue by anyosa** [apvarun/blist-hugo-theme#93]
Hi!
thanks for the template.
I wonder if there is a way to skip the thumbnail in the blog post. It is quite big and centers the entry to it instead of the words. thanks.

**Comment by apvarun** [comment]
Theme has been updated to include `hidePageThumbnail` option to enable the same. Ref: [config.toml](https://github.com/apvarun/blist-hugo-theme/blob/main/exampleSite/config.toml#L124)
