### ISSUE TITLE
bug: css on mobile view

### ISSUE THREAD

**Issue by mavogel** [apvarun/blist-hugo-theme#94]
Awesome theme 👍🏾  I love it. Thanks for releasing `v2.0.0` shortly. I am stumbling over some minor bugs, such as follows:

The element wrapping of the reading time and word count could be fixed to wrap correctly the the new line. See the screenshot

<img width="488" alt="Screenshot 2022-12-26 at 22 22 50" src="https://user-images.githubusercontent.com/8409778/209583978-5d9cb51f-41fd-4834-86db-895a44ec8bdf.png">

**Comment by apvarun** [comment]
@mavogel This has been addressed

![image](https://user-images.githubusercontent.com/8411309/209699085-a5b0c837-8824-4294-ab6b-3e72942bf73e.png)

**Comment by mavogel** [comment]
Awesome :) Thanks for the fast fix
